# Generated by Django 4.2 on 2023-06-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('number', models.PositiveIntegerField()),
                ('token', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='UserNew',
        ),
    ]
